/**
 * attribute_fusion_service.js
 *
 * Multi-Modal Attribute Fusion Engine — Bayesian Cross-Validation of
 * Physical Hair Evidence (Modality 1) with HIrisPlex-S DNA Predictions (Modality 2).
 *
 * In forensic casework, a hair strand recovered at a crime scene provides two
 * independent information channels:
 *   1. Physical/macroscopic observation (colour, texture — documented in the
 *      scene report, no lab equipment required).
 *   2. Genomic profile extracted from the hair root sheath, here represented
 *      by synthetic HIrisPlex-S SNP markers (rs12913832, rs1800407, …) whose
 *      privacy-safe synthetic equivalents are generated by dna_service.js.
 *
 * The Weighted Log-Opinion Pool (WLOP) fuses both channels into a single
 * posterior probability distribution that drives face synthesis.  A Concordance
 * Check then flags whether the two modalities agree (verified match) or
 * conflict (possible cosmetic alteration / environmental degradation of DNA).
 *
 * References:
 *   Walsh et al. (2013) — HIrisPlex eye/hair colour prediction system.
 *   Genest & Zidek (1986) — Combining probability distributions: A critique
 *     and an annotated bibliography. Statistical Science 1(1), 114–135.
 */

const HAIR_CLASSES = ["black", "brown", "blonde", "red"];

/**
 * Convert a raw observation (string colour name) into a probability
 * distribution using a fixed observational reliability factor γ.
 *
 * @param {string} observedColor  - One of "black"|"brown"|"blonde"|"red"
 * @param {number} gamma          - Confidence in the physical observation [0,1]
 * @returns {Record<string,number>}
 */
function observationToProbabilities(observedColor, gamma = 0.85) {
  const obs = (observedColor || "brown").toLowerCase();
  const residual = (1.0 - gamma) / (HAIR_CLASSES.length - 1);
  return Object.fromEntries(
    HAIR_CLASSES.map((c) => [c, c === obs ? gamma : residual])
  );
}

/**
 * Weighted Log-Opinion Pool (Bayesian Attribute Fusion).
 *
 * S(c) = P_DNA(c)^w_DNA  ×  P_Hair(c)^w_Hair
 * Normalised so that ΣP_Fused(c) = 1.
 *
 * @param {Record<string,number>} pDna   - HIrisPlex-S hair colour probabilities
 * @param {Record<string,number>} pHair  - Physical evidence probabilities
 * @param {number}                wDna   - Weight assigned to DNA modality
 * @param {number}                wHair  - Weight assigned to physical evidence
 * @returns {{ fusedProbabilities: Record<string,number>, fusedHairColor: string }}
 */
function weightedLogOpinionPool(pDna, pHair, wDna, wHair) {
  const raw = {};
  let total = 0;

  HAIR_CLASSES.forEach((c) => {
    const pD = Math.max(pDna[c] ?? 0.25, 1e-9); // guard against log(0)
    const pH = Math.max(pHair[c] ?? 0.25, 1e-9);
    const score = Math.pow(pD, wDna) * Math.pow(pH, wHair);
    raw[c] = score;
    total += score;
  });

  let bestClass = HAIR_CLASSES[0];
  let maxP = -1;
  const fusedProbabilities = {};

  HAIR_CLASSES.forEach((c) => {
    const p = total > 0 ? raw[c] / total : 0.25;
    fusedProbabilities[c] = Number(p.toFixed(4));
    if (fusedProbabilities[c] > maxP) {
      maxP = fusedProbabilities[c];
      bestClass = c;
    }
  });

  return { fusedProbabilities, fusedHairColor: bestClass };
}

/**
 * Main fusion entry-point.
 *
 * @param {object} opts
 * @param {string} opts.observedHairColor      - Physical hair colour from crime-scene record
 * @param {Record<string,number>} opts.dnaHairProbabilities  - P(hairColor|SNPs) from HIrisPlex-S
 * @param {number} [opts.dnaCompleteness=1.0]  - 0–1 fraction of expected SNPs present; lower
 *                                               values shift weight toward physical evidence
 * @param {number} [opts.observationalGamma=0.85]  - Reliability of the physical observation
 * @returns {{
 *   fusedHairColor: string,
 *   fusedProbabilities: Record<string,number>,
 *   crossValidation: {
 *     isConcordant: boolean,
 *     status: string,
 *     physicalEvidence: string,
 *     dnaTopPrediction: string,
 *     confidence: number,
 *     notes: string
 *   },
 *   weights: { dna: number, hair: number },
 *   fusionMethod: string
 * }}
 */
export function fuseHairAndDna({
  observedHairColor,
  dnaHairProbabilities = {},
  dnaCompleteness = 1.0,
  observationalGamma = 0.85,
} = {}) {
  const obs = (observedHairColor || "brown").toLowerCase();

  // --- Weights: DNA gets up to 0.60, scaled by how complete the SNP panel is.
  //     Physical evidence picks up the slack when DNA is partial / degraded.
  const wDna  = Math.min(0.60, 0.40 + 0.20 * Math.max(0, Math.min(1, dnaCompleteness)));
  const wHair = 1.0 - wDna;

  const pHair = observationToProbabilities(obs, observationalGamma);

  // Fill missing DNA probabilities with a uniform prior
  const pDna = Object.fromEntries(
    HAIR_CLASSES.map((c) => [c, dnaHairProbabilities[c] ?? 0.25])
  );

  const { fusedProbabilities, fusedHairColor } = weightedLogOpinionPool(
    pDna, pHair, wDna, wHair
  );

  // --- Concordance Check ---
  const dnaTopEntry = Object.entries(pDna).reduce((a, b) =>
    b[1] > a[1] ? b : a, ["unknown", 0]
  );
  const dnaTopPrediction = dnaTopEntry[0];
  const isConcordant = dnaTopPrediction === obs;

  let status, notes;
  if (isConcordant) {
    status = "CONCORDANT_VERIFIED";
    notes =
      `Physical hair evidence (${obs}) matches HIrisPlex-S genetic prediction (${dnaTopPrediction}). ` +
      `Multi-modal fusion confidence boosted. Composite reflects the verified natural phenotype.`;
  } else {
    status = "DISCORDANCE_DETECTED";
    notes =
      `⚠️ Physical evidence (${obs}) conflicts with genetic prediction (${dnaTopPrediction}). ` +
      `Possible causes: cosmetic hair dye / bleaching, environmental pigment degradation, or ` +
      `partial DNA template dropout. Dual composite variations recommended — one for each modality.`;
  }

  return {
    fusedHairColor,
    fusedProbabilities,
    crossValidation: {
      isConcordant,
      status,
      physicalEvidence: obs,
      dnaTopPrediction,
      confidence: Number((fusedProbabilities[fusedHairColor] * 100).toFixed(1)),
      notes,
    },
    weights: { dna: Number(wDna.toFixed(3)), hair: Number(wHair.toFixed(3)) },
    fusionMethod:
      "Bayesian Weighted Log-Opinion Pool — Physical Hair Evidence × HIrisPlex-S Genomic Prediction",
  };
}
