import { motion } from 'framer-motion';

export default function EthicsPage() {
  return (
    <div className="p-8 max-w-4xl mx-auto text-gray-300 space-y-8">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="text-center">
        <h2 className="text-4xl font-bold neon-text text-white mb-4">Ethical Guidelines & Disclaimers</h2>
        <p className="text-lg">Strict adherence to moral and legal frameworks for synthetic forensic analysis.</p>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass-panel p-6 rounded-xl border border-red-500/50 shadow-[0_0_15px_rgba(255,0,0,0.1)]">
        <h3 className="text-xl font-semibold text-white mb-3 flex items-center gap-2">
          <span className="text-red-500">⚠️</span> Non-Admissibility in Real Investigations
        </h3>
        <p className="text-sm leading-relaxed">
          The facial representations generated by this Conditional GAN system are **strictly for educational, research, and simulation purposes**. The outputs are probabilistic approximations based on genetic markers and cannot be used as definitive evidence in a court of law or active criminal investigations. This tool demonstrates technological capabilities and does not assert absolute factual accuracy of a suspect's identity.
        </p>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-panel p-6 rounded-xl border border-gray-700">
        <h3 className="text-xl font-semibold text-white mb-3">Data Bias & Demographic Imbalance</h3>
        <p className="text-sm leading-relaxed">
          The underlying AI models (including those trained on datasets like CelebA) inherently contain demographic biases. These datasets disproportionately represent certain ethnicities, ages, and facial structures, which may lead to skewed or inaccurate generations for underrepresented groups. Operatives must actively acknowledge these biases when interpreting the synthesized data.
        </p>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-panel p-6 rounded-xl border border-gray-700">
        <h3 className="text-xl font-semibold text-white mb-3">Privacy & Genetic Autonomy</h3>
        <p className="text-sm leading-relaxed">
          The extraction and synthesis of visual traits from DNA (phenotyping) raise profound privacy concerns. Generating a face from biological material fundamentally intersects with an individual's right to genetic anonymity. This simulation assumes explicit consent or legally sanctioned environments (e.g., severe criminal cases) and should not be weaponized for mass surveillance.
        </p>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-panel p-6 rounded-xl border border-gray-700">
        <h3 className="text-xl font-semibold text-white mb-3">AI-Generated Uncertainty</h3>
        <p className="text-sm leading-relaxed">
          While the mapping of genes to physical traits (e.g., HIrisPlex-S) is rooted in forensic science, translating those traits into a full facial topology via Neural Networks introduces significant latency and hallucination. The confidence scores provided (e.g., 93% Match) represent the model's adherence to the latent space conditioning, **not** the real-world statistical probability of a perfect match.
        </p>
      </motion.div>
    </div>
  );
}
